import Mathlib.Tactic
import Mathlib.Analysis.Convex.SimplicialComplex.Basic

variable {E 𝕜 : Type _}
variable [Ring 𝕜] [PartialOrder 𝕜] [AddCommGroup E] [Module 𝕜 E]

theorem face_nonempty
    (X : Geometry.SimplicialComplex 𝕜 E)
    (s : Finset E)
  : s ∈ X.faces → s ≠ ∅ :=
by
  contrapose
  intro s_empty
  rw [s_empty]
  apply X.empty_notMem

theorem vertices_setOf
    (X : Geometry.SimplicialComplex 𝕜 E)
  : X.vertices = {x : E | ∃ s ∈ X.faces, x ∈ s} :=
by
  simp only [Set.ext_iff, Set.mem_setOf]
  intros v
  constructor
  { intros v_in_X
    use {v}
    constructor
    assumption
    rw [Finset.mem_singleton] }
  { intros v_in_s
    choose s s_in_X v_in_s using v_in_s
    have v_set_in_s : {v} ∈ X.faces :=
    by
      apply X.down_closed s_in_X
      rw [Finset.singleton_subset_iff]
      assumption
      simp only [Finset.nonempty_iff_ne_empty, ne_eq, Finset.singleton_ne_empty, not_false_eq_true]
    assumption }

instance vertices.Finite [DecidableEq E]
    (X : Geometry.SimplicialComplex 𝕜 E) [Finite X.faces]
  : Finite X.vertices :=
by
  rw [Geometry.SimplicialComplex.vertices_eq]
  rw [Set.biUnion_eq_iUnion]
  apply Set.finite_iUnion
  intros s_in_X
  simp only [Finset.finite_toSet]

theorem simplex_subset_vertices
    (X : Geometry.SimplicialComplex 𝕜 E)
    (s : Finset E)
  : s ∈ X.faces → ↑s ⊆ X.vertices :=
by
  intro s_in_X
  rw [vertices_setOf, Set.subset_def]
  intro x x_in_s
  rw [Set.mem_setOf]
  use s; constructor <;> assumption

instance vertices.FintypeConverse [DecidableEq E]
    (X : Geometry.SimplicialComplex 𝕜 E) [X_dec : DecidablePred fun s => s ∈ X.faces]
  : Fintype X.vertices → Fintype X.faces :=
by
  intro fin_vert_X
  apply Set.fintypeSubset ↑(Finset.powerset (@Set.toFinset _ (X.vertices) fin_vert_X))
  rw [Set.subset_def]
  intro s s_in_X
  rw [Finset.mem_coe, Finset.mem_powerset, Set.subset_toFinset]
  apply simplex_subset_vertices
  assumption

instance vertices.Fintype [DecidableEq E]
    (X : Geometry.SimplicialComplex 𝕜 E) [Fintype X.faces]
  : Fintype X.vertices :=
by
  rw [Geometry.SimplicialComplex.vertices_eq, Set.biUnion_eq_iUnion]
  apply Set.fintypeiUnion

theorem simplex_mem_is_vertex
    (X : Geometry.SimplicialComplex 𝕜 E)
    (s : Finset E) (x : E)
    (s_in_X : s ∈ X.faces)
    (x_in_s : x ∈ s)
  : x ∈ X.vertices :=
by
  rw [vertices_setOf, Set.mem_setOf]
  use s

theorem vertex_iff_in_simplex
    (X : Geometry.SimplicialComplex 𝕜 E) (x : E)
  : x ∈ X.vertices ↔ ∃ s ∈ X.faces, x ∈ s := by rw [vertices_setOf, Set.mem_setOf]

theorem vertices_bot : (⊥ : Geometry.SimplicialComplex 𝕜 E).vertices = ∅ :=
by
  rw [vertices_setOf, Set.eq_empty_iff_forall_notMem]
  intro x
  simp only [Set.mem_setOf, not_exists, Set.mem_singleton_iff]
  intro s
  rw [not_and]
  intro s_empty
  rw [Geometry.SimplicialComplex.faces_bot] at s_empty
  contradiction

theorem vertices_congr
    (X Y : Geometry.SimplicialComplex 𝕜 E)
  : X.faces = Y.faces → X.vertices = Y.vertices :=
by
  intro X_eq_Y
  simp only [vertices_setOf, X_eq_Y]

-- The simplex generated by a finset
def simplex_faces (V : Finset E) := V.powerset.toSet \ {∅}

theorem simplex_empty_notMem
    {V : Finset E}
  : ∅ ∉ simplex_faces V :=
by
  unfold simplex_faces
  rw [Set.mem_diff, not_and]
  intros empty_in_power
  tauto

theorem simplex_indep
    {V : Finset E}
  : ∀ {s}, s ∈ simplex_faces V → AffineIndependent 𝕜 ((↑) : s → E) :=
by
  sorry

theorem simplex_down_closed
    {V : Finset E}
  : ∀ {s t}, s ∈ simplex_faces V → t ⊆ s → t.Nonempty → t ∈ simplex_faces V :=
by
  unfold simplex_faces
  intros s t s_simplex t_sset_s t_nonempty
  rw [Set.mem_diff] at ⊢ s_simplex
  choose s_in_power s_nin_empty using s_simplex
  constructor

  rw [Finset.mem_coe, Finset.mem_powerset] at ⊢ s_in_power
  transitivity s <;> assumption

  rw [Set.mem_singleton_iff, ← ne_eq, ← Finset.nonempty_iff_ne_empty]
  assumption

theorem simplex_inter_subset_convexHull
    {V : Finset E}
  : ∀ {s t}, s ∈ simplex_faces V → t ∈ simplex_faces V →
      convexHull 𝕜 ↑s ∩ convexHull 𝕜 ↑t ⊆ convexHull 𝕜 (s ∩ t : Set E) :=
by
  sorry

@[simp]
def simplex (V : Finset E) : Geometry.SimplicialComplex 𝕜 E :=
  ⟨V.powerset.toSet \ {∅}, simplex_empty_notMem, simplex_indep, simplex_down_closed, simplex_inter_subset_convexHull⟩

instance simplex.Finite (s : Finset E) : Finite (@simplex E 𝕜 _ _ _ _ s).faces :=
by
  simp only [simplex, Finite.Set.finite_diff]

instance simplex.Fintype [DecidableEq E] (s : Finset E) : Fintype (@simplex E 𝕜 _ _ _ _ s).faces :=
by
  simp only [simplex]
  apply Set.fintypeDiff

theorem simplex_vertices
    (s : Finset E)
  : (@simplex E 𝕜 _ _ _ _ s).vertices = s :=
by
  rw [vertices_setOf]
  simp only [Set.ext_iff, Set.mem_setOf, simplex]
  intro y
  constructor
  intro y_in_union
  choose t t_in_simplex y_in_t using y_in_union
  simp only [Set.mem_diff, Finset.mem_coe, Finset.mem_powerset, Finset.subset_iff] at t_in_simplex
  choose t_in_simplex t_nonempty using t_in_simplex
  specialize t_in_simplex y_in_t
  rw [Finset.mem_coe]
  assumption
  intro y_in_s
  use s; constructor
  rw [Set.mem_diff, Finset.mem_coe]
  constructor
  apply Finset.mem_powerset_self
  simp only [Set.mem_singleton_iff]
  simp only[Finset.eq_empty_iff_forall_notMem, not_forall, not_not]
  rw [Finset.mem_coe] at y_in_s
  use y
  assumption

/-
# Subcomplexes
-/
-- Define a subcomplex in the usual way:
-- i.e., simplices are contained in the other.

-- TODO: Replaced by ≤ lattice notation? Not clear to me how to use it.
def IsSubcomplex
    (X Y : Geometry.SimplicialComplex 𝕜 E)
  : Prop :=
    X.faces ⊆ Y.faces

@[reducible]
instance Geometry.SimplicialComplex.instHasSubset : HasSubset (Geometry.SimplicialComplex 𝕜 E) :=
  ⟨IsSubcomplex⟩

theorem is_subcomplex_vertex
    (X Y : Geometry.SimplicialComplex 𝕜 E)
    (Y_subcomp_X : Y ⊆ X)
  : ∀ x : E, x ∈ Y.vertices → x ∈ X.vertices :=
by
  simp only [Geometry.SimplicialComplex.instHasSubset, IsSubcomplex, Set.subset_def] at Y_subcomp_X
  intro y y_in_vert_Y
  simp only [Geometry.SimplicialComplex.vertices_eq, Set.mem_iUnion] at y_in_vert_Y ⊢
  choose s Hs y_in_s using y_in_vert_Y
  specialize Y_subcomp_X s Hs
  use s

theorem is_subcomplex_vertices
    (X Y : Geometry.SimplicialComplex 𝕜 E)
    (Y_subcomp_X : Y ⊆ X)
  : Y.vertices ⊆ X.vertices := by
  simp only [Set.subset_def]
  apply is_subcomplex_vertex X Y Y_subcomp_X

-- Equivalent, useful definition of a simplex as a subcomplex of the original.
def IsSimplex
    (X : Geometry.SimplicialComplex 𝕜 E)
    (s : Finset E)
  : Prop :=
    simplex s ⊆ X

theorem simplex_iff_subcomplex_mem
    (X : Geometry.SimplicialComplex 𝕜 E)
    (s : Finset E) [Nonempty s]
  : s ∈ X.faces ↔ simplex s ⊆ X :=
by
  constructor
  intro s_in_X_simpl
  simp only [IsSubcomplex, simplex, Geometry.SimplicialComplex.instHasSubset]
  rw [Set.subset_def]
  intro x x_in_s_power
  rw [Set.mem_diff, Finset.mem_coe, Finset.mem_powerset] at x_in_s_power
  choose x_sset_s x_nonempty using x_in_s_power
  apply X.down_closed s_in_X_simpl
  assumption
  rw [Set.mem_singleton_iff, ← ne_eq, ← Finset.nonempty_iff_ne_empty] at x_nonempty
  assumption
  intro s_simpl_X
  simp only [IsSubcomplex, simplex, Geometry.SimplicialComplex.instHasSubset] at s_simpl_X
  rw [Set.subset_def] at s_simpl_X
  specialize s_simpl_X s
  rw [Set.mem_diff, Finset.mem_coe] at s_simpl_X
  specialize s_simpl_X
    (by
      constructor
      apply Finset.mem_powerset_self s
      simp only [Set.mem_singleton_iff, ← Finset.nonempty_iff_ne_empty, ← Finset.nonempty_coe_sort]
      assumption)
  assumption

theorem simplex_if_in_subcomplex
    (X Y : Geometry.SimplicialComplex 𝕜 E)
    (s : Finset E)
  : s ∈ X.faces → X ⊆ Y → s ∈ Y.faces :=
by
  intro s_in_X X_sub_Y
  simp only [Geometry.SimplicialComplex.instHasSubset, IsSubcomplex, Set.subset_def] at X_sub_Y
  specialize X_sub_Y s s_in_X
  assumption
