/-
Copyright (c) 2022 Clara Löh. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.txt.
Author: Clara Löh.
-/

import tactic          -- standard proof tactics
import data.set        -- basics on sets
import data.set.finite -- basics on finite sets
import data.finset     -- type-level finite sets
import data.finset.slice
import .simplicial_complex     -- basics on simplicial complexes
import .fin_simplicial_complex -- basics on finite simplicial complexes

open classical  -- we work in classical logic


/-
# Generating finite simplicial complexes
-/

/- Give a finset of finsets,
   we can construct the corresponding (finite) simplicial complex.
-/

-- the set of simplices generated by a finset of finsets
@[simp]
def fingen_simplices
    {a : Type*} [decidable_eq a]
    (S : finset (finset a))
  : finset (finset a)
:= S.bUnion (λ x, finset.powerset x)    

-- this set is indeed closed under subsets
lemma fingen_simplices_sub_closed
      {a : Type*} [decidable_eq a]
      (S : finset (finset a))
    : is_subset_closed ( ↑(fingen_simplices S) : set (finset a) ) 
:=    
begin
  assume s : finset a,
  assume s_in_gS: s ∈ fingen_simplices S,

  assume t : finset a,
  assume t_sub_s : t ⊆ s,

  show t ∈ ↑(fingen_simplices S), from
  begin
    simp only[fingen_simplices, finset.mem_coe, 
              finset.mem_bUnion, finset.mem_powerset] at *,
    rcases s_in_gS with ⟨ s' : finset a, ⟨ s'_in_S, s_sub_s'⟩⟩,

    -- We use s' as witness that t lies in fingen_simplices S
    use s',
    show _, by exact ⟨ s'_in_S, by tauto ⟩,
  end,
end

def fingen_simplicial_complex
    {a : Type*} [decidable_eq a]
    (S : finset (finset a))
  : fin_simplicial_complex a
:= fin_simplicial_complex.mk
     (fingen_simplices S)
     (fingen_simplices_sub_closed S)    

/-
# Examples
-/

-- As a basic tool to look at generated examples: 
-- extracting the simplices of a given (non-negative) dimension
def simplices_of_dim 
    {a : Type*}
    (X : fin_simplicial_complex a)
    (n : nat)
  : finset (finset a)
:= X.simplices.slice (n+1)


-- Cylinder

def cylinder 
  : fin_simplicial_complex nat
:= fingen_simplicial_complex 
     { {0,1,4}, {0,3,4}, {1,2,5}, {1,4,5}, {2,3,0}, {2,5,3} }  

#eval cylinder.simplices
/- {{0, 1, 4}, {0, 1}, {0, 2, 3}, {0, 2}, {0, 3, 4}, {0, 3}, 
   {0, 4}, {0}, {1, 2, 5}, {1, 2}, {1, 4, 5}, {1, 4}, {1, 5}, 
   {1}, {2, 3, 5}, {2, 3}, {2, 5}, {2}, {3, 4}, {3, 5}, {3}, 
   {4, 5}, {4}, {5}, {}}
-/

#eval simplices_of_dim cylinder 0 -- {{0}, {1}, {2}, {3}, {4}, {5}}
#eval simplices_of_dim cylinder 1 -- {{0, 1}, {0, 2}, {0, 3}, {0, 4}, {1, 2}, {1, 4}, {1, 5}, {2, 3}, {2, 5}, {3, 4}, {3, 5}, {4, 5}}
#eval simplices_of_dim cylinder 2 -- {{0, 1, 4}, {0, 2, 3}, {0, 3, 4}, {1, 2, 5}, {1, 4, 5}, {2, 3, 5}}
#eval simplices_of_dim cylinder 3 -- {}

-- Moebius strip

def moebius
  : fin_simplicial_complex nat
:= fingen_simplicial_complex
    ({ {0,1,4}, {0,3,4}, {1,2,5}, {1,4,5}, {2,3,0}, {2,5,0} })  

-- Octahedron (surface)

def octahedron
  : fin_simplicial_complex nat
:= fingen_simplicial_complex
    ({ {0,1,5}, {0,1,4}
     , {1,2,5}, {1,2,4}
     , {2,3,5}, {2,3,4}
     , {3,0,5}, {3,0,4} })

-- 2-Torus

def torus
  : fin_simplicial_complex nat
:= fingen_simplicial_complex 
     { {0,1,4}, {0,3,4}, {1,2,5}, {1,4,5}, {2,0,3}, {2,5,3}
     , {3,4,7}, {3,6,7}, {4,5,8}, {4,7,8}, {5,3,6}, {5,8,6}
     , {6,7,1}, {6,0,1}, {7,8,2}, {7,1,2}, {8,6,0}, {8,2,0} } 

#eval torus.simplices 
#eval simplices_of_dim torus 0
#eval simplices_of_dim torus 1
#eval simplices_of_dim torus 2

-- Klein bottle

def klein_bottle
  : fin_simplicial_complex nat
:= fingen_simplicial_complex  
     { {0,1,4}, {0,3,4}, {1,2,5}, {1,4,5}, {2,0,6}, {2,5,6}
     , {3,4,7}, {3,6,7}, {4,5,8}, {4,7,8}, {5,3,6}, {5,8,3}
     , {6,7,1}, {6,0,1}, {7,8,2}, {7,1,2}, {8,3,0}, {8,2,0} } 

-- Projective plane

def projective_plane
  : fin_simplicial_complex nat
:= fingen_simplicial_complex  
     { {0,1,5}, {0,4,5}, {1,2,6}, {1,5,6}, {2,3,6}, {3,6,7}
     , {4,5,8}, {4,7,8}, {5,6,9}, {5,8,9}, {6,7,4}, {6,4,9}
     , {7,8,2}, {7,3,2}, {8,9,1}, {8,2,1}, {9,4,0}, {9,1,0} }

#eval finset.card (simplices_of_dim projective_plane 2) -- 18

-- Simplicial sphere of the given dimension
-- (built from proper subsets of {0,...,dim+1})

def sphere
    (n : nat)
  : fin_simplicial_complex nat
:= fingen_simplicial_complex 
     (finset.ssubsets (finset.range (n+2)))

#eval (sphere 0).simplices -- {{0}, {1}, {}}
#eval (sphere 1).simplices -- {{0, 1}, {0, 2}, {0}, {1, 2}, {1}, {2}, {}}
#eval (sphere 2).simplices -- ...
#eval simplices_of_dim (sphere 3) 3
      -- {{0, 1, 2, 3}, {0, 1, 2, 4}, {0, 1, 3, 4}, {0, 2, 3, 4}, {1, 2, 3, 4}}
