-- standard proof tactics
-- standard proof tactics
import Mathlib.Tactic
-- import Set.Basic
-- import Data.Set.Finite
-- import Data.Finset.Basic

-- basics on sets
-- basics on sets
-- basics on finite sets
-- basics on finite sets
-- type-level finite sets
-- type-level finite sets
open scoped BigOperators

variable {α : Type _}

/-
# Simplicial complexes
-/
/- A simplicial complex is a set of finite sets
   that is closed under taking subsets;
   we use finsets to model these finite sets
-/
@[simp]
def IsSubsetClosed (S : Set (Finset α)) :=
  ∀ s ∈ S, ∀ t, t ⊆ s → t ∈ S

structure SimplicialComplex (α : Type _) where mk ::
  simplices : Set (Finset α)
  Nonempty : Nonempty simplices
  subset_closed : IsSubsetClosed simplices

theorem eq_simplices_subset_closed (S T : Set (Finset α)) :
    S = T → IsSubsetClosed S → IsSubsetClosed T :=
  by
  intro S_eq_T subset_closed_S
  subst S_eq_T
  exact subset_closed_S

theorem simplicialComplex_empty_simplex (X : SimplicialComplex α) : ∅ ∈ X.simplices :=
  by
  have H : Nonempty X.simplices := by apply X.Nonempty
  rw [Set.nonempty_coe_sort, Set.nonempty_def] at H
  choose s Hs using H
  apply X.subset_closed s <;> tauto

-- The empty simplicial complex
def emptySc {a : Type _} : SimplicialComplex a :=
  SimplicialComplex.mk ({∅} : Set (Finset a))
    (by rw [Set.nonempty_coe_sort, Set.nonempty_def]; use∅; simp)
    (by
      unfold IsSubsetClosed
      intro s H_empty t t_sset_s
      rw [Set.mem_singleton_iff] at H_empty
      rw [H_empty, Finset.subset_empty] at t_sset_s
      tauto)

theorem empty_type_implies_empty_complex {α : Type _} [IsEmpty α] :
    ∀ X : SimplicialComplex α, X.simplices = {∅} :=
  by
  intro X
  rw [Set.eq_singleton_iff_unique_mem]
  constructor
  apply simplicialComplex_empty_simplex
  intro s s_in_X
  apply Finset.eq_empty_of_isEmpty

instance SimplexImage.nonempty {β : Type _} [DecidableEq β] (s : Finset α) [Nonempty s]
    (f : α → β) : Nonempty ↥(Finset.image f s) :=
  by
  apply Finset.Nonempty.coe_sort
  apply Finset.Nonempty.image
  apply Finset.nonempty_coe_sort.mp
  assumption

/- The set of vertices of a simplicial complex is
   the set of all elements
   that occur in at least one of the simplices.
-/
def vertices (X : SimplicialComplex α) : Set α :=
  ⋃ (s : Finset α) (H : s ∈ X.simplices), s

theorem vertices_setOf (X : SimplicialComplex α) :
    vertices X = {x : α | ∃ s ∈ X.simplices, x ∈ s} :=
  by
  simp only [vertices, Set.ext_iff, Set.mem_iUnion, Set.mem_setOf]
  intro x
  tauto

instance vertices.fintype [DecidableEq α] (X : SimplicialComplex α) [Fintype X.simplices] :
    Fintype (vertices X) := by
  unfold vertices
  apply Set.fintypeBiUnion
  intro s s_in_X
  apply FinsetCoe.fintype

theorem simplex_subset_vertices (X : SimplicialComplex α) (s : Finset α) :
    s ∈ X.simplices → ↑s ⊆ vertices X := by
  intro s_in_X
  rw [vertices_setOf, Set.subset_def]
  intro x x_in_s
  rw [Set.mem_setOf]
  use s; constructor <;> assumption

instance vertices.fintypeConverse [DecidableEq α] (X : SimplicialComplex α)
    [X_dec : DecidablePred fun s => s ∈ X.simplices] : Fintype (vertices X) → Fintype X.simplices :=
  by
  intro fin_vert_X
  apply Set.fintypeSubset ↑(Finset.powerset (@Set.toFinset _ (vertices X) fin_vert_X))
  rw [Set.subset_def]
  intro s s_in_X
  rw [Finset.mem_coe, Finset.mem_powerset, Set.subset_toFinset]
  apply simplex_subset_vertices
  assumption

theorem vertex_iff_singleton (X : SimplicialComplex α) (x : α) :
    x ∈ vertices X ↔ {x} ∈ X.simplices := by
  constructor
  intro x_vert
  simp only [vertices, Set.mem_iUnion] at x_vert
  choose s Hs x_in_s using x_vert
  apply X.subset_closed s
  assumption
  rw [Finset.subset_iff]
  intro y y_eq_x
  rw [Finset.mem_singleton] at y_eq_x
  rw [y_eq_x] at *
  tauto
  intro x_simpl
  simp only [vertices, Set.mem_iUnion]
  use{x}
  constructor
  rw [Finset.mem_coe, Finset.mem_singleton]
  assumption

theorem simplex_mem_is_vertex (X : SimplicialComplex α) (s : Finset α) (x : α)
    (s_in_X : s ∈ X.simplices) (x_in_s : x ∈ s) : x ∈ vertices X :=
  by
  rw [vertices_setOf, Set.mem_setOf]
  use s

theorem vertex_iff_in_simplex (X : SimplicialComplex α) (x : α) :
    x ∈ vertices X ↔ ∃ s ∈ X.simplices, x ∈ s := by rw [vertices_setOf, Set.mem_setOf]

theorem emptySc_vertices : vertices (@emptySc α) = ∅ :=
  by
  rw [vertices_setOf, Set.eq_empty_iff_forall_notMem]
  intro x
  simp only [Set.mem_setOf, not_exists, emptySc, Set.mem_singleton_iff]
  intro s
  rw [not_and]
  intro s_empty
  rw [s_empty]
  simp only [Finset.notMem_empty, not_false_eq_true]

theorem vertices_congr (X Y : SimplicialComplex α) :
    X.simplices = Y.simplices → vertices X = vertices Y :=
  by
  intro X_eq_Y
  simp only [vertices_setOf, X_eq_Y]

-- The simplex generated by a finset
@[simp]
def simplex (V : Finset α) : SimplicialComplex α :=
  SimplicialComplex.mk (Finset.powerset V)
    (by
      rw [Set.nonempty_coe_sort]
      apply Finset.powerset_nonempty)
    (by simp; tauto)

instance simplex.fintype (s : Finset α) : Fintype (simplex s).simplices :=
  by
  simp only [simplex, SimplicialComplex.simplices]
  apply FinsetCoe.fintype

instance simplex.finite (s : Finset α) : Finite (simplex s).simplices :=
  by
  simp only [simplex, SimplicialComplex.simplices]
  rw [Set.finite_coe_iff]
  sorry
  -- apply Set.Finite.intro
  -- apply FinsetCoe.fintype

theorem simplex_vertices (s : Finset α) : vertices (@simplex α s) = s :=
  by
  rw [vertices_setOf]
  simp only [Set.ext_iff, Set.mem_setOf, simplex, Set.mem_singleton_iff]
  intro y
  constructor
  intro y_in_union
  choose t t_in_simplex y_in_t using y_in_union
  simp only [Finset.mem_coe, Finset.mem_powerset, Finset.subset_iff] at t_in_simplex
  specialize t_in_simplex y_in_t
  rw [Finset.mem_coe]
  assumption
  intro y_in_s
  use s; constructor
  rw [Finset.mem_coe]
  apply Finset.mem_powerset_self
  rw [Finset.mem_coe] at y_in_s
  assumption

#print stdSimplex /-
-- The standard n-simplex is generated by {0,...,n}
@[simp]
def stdSimplex (n : ℕ) : SimplicialComplex ℕ :=
  simplex (Finset.range (n + 1))
-/

/-
# Dimension of simplices and simplicial complexes
-/
-- The dimension of a simplex is just its cardinality - 1.
@[simp]
def dim (s : Finset α) : ℤ :=
  Finset.card s - 1

@[simp]
def IsKSimplex (s : Finset α) (k : ℕ) :=
  dim s = k

#eval dim (Finset.range 5)

-- 4
#eval dim (Finset.range 0)

-- -1
-- A simplicial complex has dimension n
-- if n is the maximal dimension of all simplices.
@[simp]
def HasDimensionLeq (X : SimplicialComplex α) (n : ℕ) :=
  ∀ s ∈ X.simplices, dim s ≤ n

@[simp]
def HasDimensionGeq (X : SimplicialComplex α) (n : ℕ) :=
  ∃ s ∈ X.simplices, dim s ≥ n

@[simp]
def HasDimension (X : SimplicialComplex α) (n : ℕ) :=
  HasDimensionLeq X n ∧ HasDimensionGeq X n

-- The standard n-simplex has dimension n
theorem dim_stdSimplex (n : ℕ) : HasDimension (stdSimplex n) n :=
  by
  let Dn := stdSimplex n
  -- dim ≤ n
  have dim_leq_n : HasDimensionLeq Dn n :=
    by
    intro (s : Finset Nat)
    intro (s_in_Dn : s ∈ Dn.simplices)
    -- By definition, s ⊆ {0,...,n}.
    have s_sub_n : s ⊆ Finset.range (n + 1) := finset.mem_powerset.mp s_in_Dn
    -- Thus, s has cardinality at most n + 1.
    have card_s_leq_n1 : Finset.card s ≤ n + 1 := by
      calc
        Finset.card s ≤ Finset.card (Finset.range (n + 1)) := Finset.card_le_card s_sub_n
        _ ≤ n + 1 := by finish
    -- Whence, s has dimension at most n
    show dim s ≤ n;
    exact by
      calc
        dim s = Finset.card s - 1 := by simp only [dim]
        _ ≤ n + 1 - 1 := by linarith
        _ ≤ n := by linarith
  -- dim ≥ n
  have dim_geq_n : HasDimensionGeq Dn n :=
    by
    -- We use {0,...,n} as a witness
    let s := Finset.range (n + 1)
    use s
    have s_in_Dn : s ∈ (stdSimplex n).simplices := by simp
    have dim_s : dim s ≥ n := by finish
    show _; · exact ⟨s_in_Dn, dim_s⟩
  -- alternatively: and.intro ...
  show _;
  · exact ⟨dim_leq_n, dim_geq_n⟩

theorem dim_geq_zero_iff_nonempty (s : Finset α) : 0 ≤ dim s ↔ s ≠ ∅ :=
  by
  unfold dim
  rw [Ne.def, ← Finset.card_eq_zero]
  constructor
  contrapose
  simp only [Classical.not_not]
  intro s_card_zero
  rw [s_card_zero]
  omega
  intro s_card_ne_zero
  have s_card_pos : s.card > 0 := by omega
  linarith

theorem dim_neg_one_iff_empty (s : Finset α) : dim s = -1 ↔ s = ∅ :=
  by
  unfold dim
  rw [← Finset.card_eq_zero]
  constructor
  intro s_card_neg_one
  simp only [sub_eq_neg_self, Nat.cast_eq_zero] at s_card_neg_one
  assumption
  intro s_card_zero
  rw [s_card_zero]
  simp

theorem dim_zero_iff_vertex (s : Finset α) : dim s = 0 ↔ ∃ x : α, s = {x} :=
  by
  unfold dim
  constructor
  intro s_card_minus_one
  have s_card_one : s.card = 1 := by linarith
  rw [← Finset.card_eq_one]
  assumption
  intro exists_x
  rw [← Finset.card_eq_one] at exists_x
  rw [exists_x]
  simp

theorem simplex_decomp [DecidableEq α] (s : Finset α) :
    0 < dim s → ∃ x ∈ s, ∃ t : Finset α, t = s \ {x} :=
  by
  unfold dim
  intro s_card_pos
  have s_card_gt_one : 1 < s.card := by linarith
  rw [Finset.one_lt_card] at s_card_gt_one
  choose a a_in_s b b_in_s a_ne_b using s_card_gt_one
  use a; constructor; assumption
  use s \ {a}

theorem simplex_decomp_dim [DecidableEq α] (s : Finset α) (x : α) (x_in_s : x ∈ s) :
    0 < dim s → 0 ≤ dim (s \ {x}) := by
  unfold dim
  intro s_card_pos
  have s_card_gt_one : 1 < s.card := by linarith
  rw [Finset.card_sdiff, Finset.card_singleton]
  apply Int.sub_nonneg_of_le
  rw [Int.ofNat_sub, Int.ofNat_one, Int.le_sub_one_iff]
  rw [Nat.one_lt_cast]
  assumption
  apply le_of_lt
  assumption
  rw [Finset.singleton_subset_iff]
  assumption

theorem simplex_decomp_dim_eq [DecidableEq α] (s : Finset α) (x : α) (x_in_s : x ∈ s) :
    0 < dim s → dim (s \ {x}) = dim s - 1 :=
  by
  unfold dim
  intro s_card_pos
  rw [Finset.card_sdiff, Finset.card_singleton]
  rw [sub_left_inj, Int.ofNat_sub, Int.ofNat_one]
  linarith
  rw [Finset.singleton_subset_iff]
  assumption

-- The dimension of a finite complex is the maximum
-- dimension of its simplices.
instance DimSet.fintype (X : SimplicialComplex α) [Fintype X.simplices] :
    Fintype (Finset.image dim X.simplices.toFinset) := by apply Set.fintypeMemFinset

theorem dim_set_nonempty (X : SimplicialComplex α) [Fintype X.simplices] :
    (Finset.image dim X.simplices.toFinset).Nonempty :=
  by
  apply Finset.Nonempty.image
  unfold Finset.Nonempty
  use∅
  rw [← Finset.mem_coe, Set.coe_toFinset]
  apply simplicialComplex_empty_simplex

@[simp]
def dimOfComplex (X : SimplicialComplex α) [Fintype X.simplices] : ℤ :=
  Finset.max' (Finset.image dim X.simplices.toFinset) (dim_set_nonempty X)

/-
# Disjointness of simplicial complexes.
-/
section Disjoint

variable [DecidableEq α]

-- Define when two simplicial complexes are disjoint via disjointness of vertices.
def DisjointComplexes (X Y : SimplicialComplex α) : Prop :=
  Disjoint (vertices X) (vertices Y)

-- Indeed, this implies simplices are disjoint, too.
theorem disjoint_simplices_iff_disj_vertices (X Y : SimplicialComplex α) (s t : Finset α)
    (s_in_X : s ∈ X.simplices) (t_in_Y : t ∈ Y.simplices) : DisjointComplexes X Y → Disjoint s t :=
  by
  simp only [DisjointComplexes, vertices]
  intro XY_disj
  rw [Set.disjoint_iff_inter_eq_empty, ← Set.subset_empty_iff] at XY_disj
  rw [Finset.disjoint_iff_inter_eq_empty, ← Finset.subset_empty, ← Finset.coe_subset,
    Finset.coe_empty, Finset.coe_inter]
  apply
    @Set.Subset.trans _ _
      ((⋃ (s : Finset α) (H : s ∈ X.simplices), ↑s) ∩ ⋃ (s : Finset α) (H : s ∈ Y.simplices), ↑s)
  apply Set.inter_subset_inter <;> apply Set.subset_biUnion_of_mem <;> assumption
  assumption

-- Disjoint singletons are also disjoint.
theorem disjoint_singleton (X : SimplicialComplex α) (x : α) :
    x ∉ vertices X → DisjointComplexes X (simplex {x}) :=
  by
  simp only [DisjointComplexes, simplex_vertices {x}]
  intro x_nin_X
  rw [Set.disjoint_iff_inter_eq_empty, Finset.coe_singleton, Set.inter_singleton_eq_empty]
  assumption

end Disjoint

/-
# Operators on simplicial complexes.
-/
section Operators

variable [DecidableEq α]

@[simp]
def simplicialUnion (X Y : SimplicialComplex α) : SimplicialComplex α :=
  SimplicialComplex.mk (X.simplices ∪ Y.simplices)
    (by
      rw [Set.nonempty_coe_sort]
      rw [Set.union_nonempty]
      left
      rw [← Set.nonempty_coe_sort]
      apply X.nonempty)
    (by
      unfold IsSubsetClosed
      intro s s_in_XY t t_sset_s
      rw [Set.mem_union] at *
      cases' s_in_XY with s_in_X s_in_Y
      left
      apply X.subset_closed s <;> assumption
      right
      apply Y.subset_closed s <;> assumption)

@[reducible]
instance : Union (SimplicialComplex α) :=
  ⟨simplicialUnion⟩

instance simplicialUnion.fintype (X Y : SimplicialComplex α) [Fintype X.simplices]
    [Fintype Y.simplices] : Fintype (X ∪ Y).simplices :=
  by
  simp only [simplicialUnion]
  apply Set.fintypeUnion

theorem simplicial_union_assoc (X Y Z : SimplicialComplex α) : X ∪ Y ∪ Z = X ∪ (Y ∪ Z) :=
  by
  simp
  rw [Set.union_assoc]

theorem simplicial_union_comm (X Y : SimplicialComplex α) : X ∪ Y = Y ∪ X :=
  by
  simp
  rw [Set.union_comm]

theorem simplicial_union_simplices (X Y : SimplicialComplex α) :
    (X ∪ Y).simplices = X.simplices ∪ Y.simplices := by simp only [simplicialUnion]

theorem simplicial_union_dim (X Y : SimplicialComplex α) [Fintype X.simplices]
    [Fintype Y.simplices] : dimOfComplex (X ∪ Y) = max (dimOfComplex X) (dimOfComplex Y) :=
  by
  unfold dimOfComplex
  apply le_antisymm
  · apply Finset.max'_le
    intro y y_in_img
    simp only [Finset.mem_image, simplicialUnion, Set.mem_union, Set.mem_toFinset] at y_in_img
    choose s s_in_union dim_s_y using y_in_img
    rw [le_max_iff]
    cases' s_in_union with s_in_X s_in_Y
    left
    apply Finset.le_max'
    rw [Finset.mem_image]
    use s; constructor
    rw [Set.mem_toFinset]
    assumption
    assumption
    right
    apply Finset.le_max'
    rw [Finset.mem_image]
    use s; constructor
    rw [Set.mem_toFinset]
    assumption
    assumption
  · rw [max_le_iff]
    constructor
    rw [Finset.max'_le_iff]
    intro y y_in_img
    simp only [Finset.mem_image, Set.mem_toFinset] at y_in_img
    choose s s_in_X dim_s_y using y_in_img
    apply Finset.le_max'
    simp only [Finset.mem_image, simplicialUnion, Set.mem_union, Set.mem_toFinset]
    use s; constructor
    left; assumption
    assumption
    rw [Finset.max'_le_iff]
    intro y y_in_img
    simp only [Finset.mem_image, Set.mem_toFinset] at y_in_img
    choose s s_in_Y dim_s_y using y_in_img
    apply Finset.le_max'
    simp only [Finset.mem_image, simplicialUnion, Set.mem_union, Set.mem_toFinset]
    use s; constructor
    right; assumption
    assumption

@[simp]
def simplicialInter (X Y : SimplicialComplex α) : SimplicialComplex α :=
  SimplicialComplex.mk (X.simplices ∩ Y.simplices)
    (by
      rw [Set.nonempty_coe_sort]
      rw [Set.inter_nonempty]
      use∅
      constructor <;> apply simplicialComplex_empty_simplex)
    (by
      unfold IsSubsetClosed
      intro s s_in_XY t t_sset_s
      rw [Set.mem_inter_iff] at *
      cases' s_in_XY with s_in_X s_in_Y
      constructor
      apply X.subset_closed s <;> assumption
      apply Y.subset_closed s <;> assumption)

@[reducible]
instance : Inter (SimplicialComplex α) :=
  ⟨simplicialInter⟩

theorem simplicial_inter_assoc (X Y Z : SimplicialComplex α) : X ∩ Y ∩ Z = X ∩ (Y ∩ Z) :=
  by
  simp
  rw [Set.inter_assoc]

theorem simplicial_inter_comm (X Y : SimplicialComplex α) : X ∩ Y = Y ∩ X :=
  by
  simp
  rw [Set.inter_comm]

end Operators

/-
# Subcomplexes
-/
-- Define a subcomplex in the usual way:
-- i.e., simplices are contained in the other.
def IsSubcomplex (X Y : SimplicialComplex α) : Prop :=
  X.simplices ⊆ Y.simplices

@[reducible]
instance : HasSubset (SimplicialComplex α) :=
  ⟨IsSubcomplex⟩

theorem is_subcomplex_vertex (X Y : SimplicialComplex α) (Y_subcomp_X : Y ⊆ X) :
    ∀ x : α, x ∈ vertices Y → x ∈ vertices X :=
  by
  simp only [vertices]
  simp only [SimplicialComplex.hasSubset, IsSubcomplex, Set.subset_def] at Y_subcomp_X
  intro y y_in_vert_Y
  simp only [Set.mem_iUnion] at y_in_vert_Y ⊢
  choose s Hs y_in_s using y_in_vert_Y
  specialize Y_subcomp_X s Hs
  use s; constructor; apply Y_subcomp_X
  apply y_in_s

theorem is_subcomplex_vertices (X Y : SimplicialComplex α) (Y_subcomp_X : Y ⊆ X) :
    vertices Y ⊆ vertices X := by
  simp only [Set.subset_def]
  apply is_subcomplex_vertex X Y Y_subcomp_X

-- Equivalent, useful definition of a simplex as a subcomplex of the original.
def IsSimplex (s : Finset α) (X : SimplicialComplex α) : Prop :=
  simplex s ⊆ X

@[reducible]
instance : Membership (Finset α) (SimplicialComplex α) :=
  ⟨IsSimplex⟩

theorem simplex_iff_subcomplex_mem (X : SimplicialComplex α) (s : Finset α) :
    s ∈ X.simplices ↔ simplex s ⊆ X := by
  constructor
  intro s_in_X_simpl
  simp only [IsSubcomplex, simplex]
  rw [Set.subset_def]
  intro x x_in_s_power
  apply X.subset_closed s
  assumption
  rw [Finset.mem_coe, Finset.mem_powerset] at x_in_s_power
  assumption
  intro s_simpl_X
  simp only [IsSubcomplex, simplex] at s_simpl_X
  rw [Set.subset_def] at s_simpl_X
  specialize s_simpl_X s
  rw [Finset.mem_coe] at s_simpl_X
  specialize s_simpl_X (Finset.mem_powerset_self s)
  assumption

-- This is, in fact, equivalent to our definition.
theorem simplex_iff_subcomplex (X : SimplicialComplex α) (s : Finset α) : s ∈ X.simplices ↔ s ∈ X :=
  by
  simp only [IsSimplex]
  apply simplex_iff_subcomplex_mem

theorem simplicial_union_eq_left_iff_subcomplex (X Y : SimplicialComplex α) [DecidableEq α] :
    (X ∪ Y).simplices = X.simplices ↔ Y ⊆ X :=
  by
  simp only [simplicialUnion, IsSubcomplex]
  apply Set.union_eq_left

theorem simplicial_union_eq_right_iff_subcomplex (X Y : SimplicialComplex α) [DecidableEq α] :
    (X ∪ Y).simplices = Y.simplices ↔ X ⊆ Y :=
  by
  simp only [simplicialUnion, IsSubcomplex]
  apply Set.union_eq_right

theorem subcomplex_simplicial_union_left_simplices [DecidableEq α] (X Y : SimplicialComplex α) :
    ∀ s : Finset α, s ∈ X.simplices → s ∈ (X ∪ Y).simplices := by apply Set.subset_union_left

theorem subcomplex_simplicial_union_left [DecidableEq α] (X Y : SimplicialComplex α) : X ⊆ X ∪ Y :=
  by
  simp only [IsSubcomplex, simplicialUnion]
  apply Set.subset_union_left

theorem subcomplex_simplicial_union_right_simplices [DecidableEq α] (X Y : SimplicialComplex α) :
    ∀ s : Finset α, s ∈ Y.simplices → s ∈ (X ∪ Y).simplices := by apply Set.subset_union_right

theorem subcomplex_simplicial_union_right (X Y : SimplicialComplex α) [DecidableEq α] : Y ⊆ X ∪ Y :=
  by
  simp only [IsSubcomplex, simplicialUnion]
  apply Set.subset_union_right

theorem simplex_if_in_subcomplex (X Y : SimplicialComplex α) (s : Finset α) :
    s ∈ X.simplices → X ⊆ Y → s ∈ Y.simplices :=
  by
  intro s_in_X X_sub_Y
  simp only [IsSubcomplex, Set.subset_def] at X_sub_Y
  specialize X_sub_Y s s_in_X
  assumption

theorem subcomplex_simplicial_inter_left_simplices [DecidableEq α] (X Y : SimplicialComplex α) :
    ∀ s : Finset α, s ∈ (X ∩ Y).simplices → s ∈ X.simplices := by apply Set.inter_subset_left

theorem subcomplex_simplicial_inter_left [DecidableEq α] (X Y : SimplicialComplex α) : X ∩ Y ⊆ X :=
  by
  simp only [IsSubcomplex, simplicialInter]
  apply Set.inter_subset_left

theorem subcomplex_simplicial_inter_right_simplices [DecidableEq α] (X Y : SimplicialComplex α) :
    ∀ s : Finset α, s ∈ (X ∩ Y).simplices → s ∈ Y.simplices := by apply Set.inter_subset_right

theorem subcomplex_simplicial_inter_right [DecidableEq α] (X Y : SimplicialComplex α) : X ∩ Y ⊆ Y :=
  by
  simp only [IsSubcomplex, simplicialInter]
  apply Set.inter_subset_right

theorem singleton_inter_eq_empty_iff_not_mem [DecidableEq α] {s : Finset α} {a : α} :
    {a} ∩ s = ∅ ↔ a ∉ s :=
  by
  simp only [Finset.eq_empty_iff_forall_not_mem, Finset.mem_inter, not_and]
  constructor
  intro as_disj
  specialize as_disj a (by apply Finset.mem_singleton_self)
  assumption
  intro a_nin_s x x_in_a
  rw [Finset.mem_singleton] at x_in_a
  rw [x_in_a]
  assumption
