/-
Copyright (c) 2022 Clara Löh. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.txt.
Author: Clara Löh.
-/

import tactic          -- standard proof tactics
import data.set        -- basics on sets
import data.set.finite -- basics on finite sets
import data.finset     -- type-level finite sets

open_locale big_operators

variables {α : Type*}

/- 
# Simplicial complexes
-/

/- A simplicial complex is a set of finite sets 
   that is closed under taking subsets;
   we use finsets to model these finite sets
-/   

@[simp]
def is_subset_closed
    (S : set (finset α))
:= ∀ s ∈ S, ∀ t, t ⊆ s → t ∈ S    

structure simplicial_complex (α : Type*)
:= mk :: (simplices : set (finset α))
         (nonempty : nonempty simplices)
         (subset_closed : is_subset_closed simplices)

lemma eq_simplices_subset_closed
    (S T : set (finset α))
  : S = T → is_subset_closed S → is_subset_closed T
:=
begin
  intros S_eq_T subset_closed_S,
  subst S_eq_T,
  exact subset_closed_S,
end

lemma simplicial_complex_empty_simplex
    (X : simplicial_complex α)
  : ∅ ∈ X.simplices
:= begin
  have H : nonempty X.simplices, by apply X.nonempty,
  rw [set.nonempty_coe_sort, set.nonempty_def] at H,
  choose s Hs using H,
  apply X.subset_closed s; tauto,
end

-- The empty simplicial complex
def empty_sc 
    {a : Type*}
  : simplicial_complex a
:= simplicial_complex.mk  
     ({∅} : set (finset a))
     (by { rw [set.nonempty_coe_sort, set.nonempty_def], use ∅, simp, })
     (begin
        unfold is_subset_closed,
        intros s H_empty t t_sset_s,
        rw [set.mem_singleton_iff] at H_empty,
        rw [H_empty, finset.subset_empty] at t_sset_s,
        tauto,
      end)

/- The set of vertices of a simplicial complex is 
   the set of all elements 
   that occur in at least one of the simplices.
-/
def vertices 
    (X : simplicial_complex α)
  : set α
:= ⋃ (s : finset α) (H : s ∈ X.simplices), s
--:= { x : α | ∃ s ∈ X.simplices, x ∈ s }

instance vertices.fintype
    [decidable_eq α]
    (X : simplicial_complex α) [fintype X.simplices]
  : fintype (vertices X)
:= begin
  unfold vertices,
  apply set.fintype_bUnion,
  intros s s_in_X,
  apply finset_coe.fintype,
end

lemma vertex_iff_singleton
    (X : simplicial_complex α)
    (x : α)
  : x ∈ vertices X ↔ {x} ∈ X.simplices
:= begin
  split,

  intro x_vert,
  simp only[vertices, set.mem_Union] at x_vert,
  choose s Hs x_in_s using x_vert,
  apply X.subset_closed s,
  assumption,
  rw [finset.subset_iff],
  intros y y_eq_x,
  rw [finset.mem_singleton] at y_eq_x,
  rw [y_eq_x] at *,
  tauto,

  intro x_simpl,
  simp only[vertices, set.mem_Union],
  use {x},
  split,
  assumption,
  rw [finset.mem_coe, finset.mem_singleton],
end

-- The simplex generated by a finset
@[simp]
def simplex
    (V : finset α)
  : simplicial_complex α
:= simplicial_complex.mk 
    (finset.powerset V)
    (begin
      rw [set.nonempty_coe_sort],
      apply finset.powerset_nonempty,
    end)
    (by { simp, tauto })

instance simplex.fintype
    (s : finset α)
  : fintype (simplex s).simplices
:= begin
  simp only [simplex, simplicial_complex.simplices],
  apply finset_coe.fintype,
end

instance simplex.finite
    (s : finset α)
  : finite (simplex s).simplices
:= begin
  simp only [simplex, simplicial_complex.simplices],
  rw [set.finite_coe_iff],
  apply set.finite.intro,
  apply finset_coe.fintype,
end

-- The standard n-simplex is generated by {0,...,n}
@[simp]
def std_simplex
    (n : ℕ)
  : simplicial_complex ℕ
:= simplex (finset.range (n + 1))

/-
# Dimension of simplices and simplicial complexes
-/

-- The dimension of a simplex is just its cardinality - 1. 
@[simp]
def dim
    (s : finset α)
  : ℤ
:= finset.card s - 1

@[simp]
def is_k_simplex
    (s : finset α)
    (k : ℕ)
:= dim s = k

#eval dim (finset.range 5) -- 4
#eval dim (finset.range 0) -- -1

-- A simplicial complex has dimension n 
-- if n is the maximal dimension of all simplices. 
@[simp]
def has_dimension_leq
    (X : simplicial_complex α)
    (n : ℕ)
:= ∀ s ∈ X.simplices, dim s ≤ n    

@[simp]
def has_dimension_geq
    (X : simplicial_complex α)
    (n : ℕ)
:= ∃ s ∈ X.simplices, dim s ≥ n    

@[simp]
def has_dimension
    (X : simplicial_complex α)
    (n : ℕ)
:= has_dimension_leq X n ∧ has_dimension_geq X n    

-- The standard n-simplex has dimension n
lemma dim_std_simplex
    (n : ℕ)
  : has_dimension (std_simplex n) n
:= begin
  let Dn := std_simplex n,

  -- dim ≤ n
  have dim_leq_n : has_dimension_leq Dn n, from
  begin
    assume s : finset nat,
    assume s_in_Dn : s ∈ Dn.simplices,

    -- By definition, s ⊆ {0,...,n}.
    have s_sub_n : s ⊆ finset.range (n+1), 
         by exact finset.mem_powerset.mp s_in_Dn,
    
    -- Thus, s has cardinality at most n + 1.
    have card_s_leq_n1 : finset.card s ≤ n + 1, from
    begin
      calc finset.card s ≤ finset.card (finset.range (n+1)) 
                         : by exact finset.card_le_of_subset s_sub_n
                     ... ≤ n + 1 
                         : by finish,
    end,

    -- Whence, s has dimension at most n
    show dim s ≤ n, from
    begin      
      calc dim s = finset.card s - 1 : by simp only [dim]
             ... ≤ n + 1 - 1         : by linarith 
             ... ≤ n                 : by linarith,
    end,
  end,

  -- dim ≥ n
  have dim_geq_n : has_dimension_geq Dn n, from
  begin
    -- We use {0,...,n} as a witness
    let s := finset.range (n+1),
    use s,

    have s_in_Dn : s ∈ (std_simplex n).simplices, 
         by simp,

    have dim_s : dim s ≥ n, 
         by finish,

    show _, by exact ⟨s_in_Dn, dim_s⟩, -- alternatively: and.intro ...
  end,

  show _, by exact ⟨dim_leq_n, dim_geq_n⟩,
end

lemma dim_neg_one_iff_empty
    (s : finset α)
  : dim s = -1 ↔ s = ∅
:= sorry

lemma dim_zero_iff_vertex
    (s : finset α)
  : dim s = 0 ↔ ∃ x : α, s = {x}
:= sorry

lemma simplex_decomp [decidable_eq α]
    (s : finset α)
  : 0 < dim s → ∃ (x ∈ s) (t : finset α), t = s \ {x}
:= sorry

lemma simplex_decomp_dim [decidable_eq α]
    (s : finset α)
    (x : α)
    (x_in_s : x ∈ s)
  : 0 < dim s → 0 ≤ dim (s \ {x})
:= sorry

lemma simplex_decomp_dim_eq [decidable_eq α]
    (s : finset α)
    (x : α)
    (x_in_s : x ∈ s)
  : 0 < dim s → dim (s \ {x}) = dim s - 1
:= sorry

-- The dimension of a finite complex is the maximum
-- dimension of its simplices.
@[simp]
def dim_of_complex
    (X : simplicial_complex α) [fintype X.simplices]
  : int
:= match finset.max (finset.bUnion X.simplices.to_finset (λ s, {dim s})) with
    | option.none := -1   -- degenerate ∅ case
    | option.some z := z
  end

/-
# Disjointness of simplicial complexes.
-/
section disjoint

variable [decidable_eq α]

-- Define when two simplicial complexes are disjoint via disjointness of vertices.
def disjoint_complexes
    (X Y : simplicial_complex α)
  : Prop
:= disjoint (vertices X) (vertices Y)

-- Indeed, this implies simplices are disjoint, too.
lemma disjoint_simplices_iff_disj_vertices
    (X Y : simplicial_complex α)
    (s t : finset α)
    (s_in_X : s ∈ X.simplices)
    (t_in_Y : t ∈ Y.simplices)
  : disjoint_complexes X Y → disjoint s t
:= begin
  simp only[disjoint_complexes, disjoint, vertices],
  intros X_disj_Y x,
  specialize X_disj_Y (↑x),

  use ↑x,
  all_goals { sorry, },
end

-- Disjoint singletons are also disjoint.
lemma disjoint_singleton
    (X : simplicial_complex α)
    (x : α)
  : x ∉ vertices X → disjoint_complexes X (simplex {x})
:= begin
  sorry
end

end disjoint

/-
# Operators on simplicial complexes.
-/

section operators

variables [decidable_eq α]

@[simp]
def simplicial_union
    (X Y : simplicial_complex α)
  : simplicial_complex α
:= simplicial_complex.mk
    (X.simplices ∪ Y.simplices)
    (begin
      rw [set.nonempty_coe_sort],
      rw [set.union_nonempty],
      left,
      rw [←set.nonempty_coe_sort],
      apply X.nonempty,
    end)
    (begin
      unfold is_subset_closed,
      intros s s_in_XY t t_sset_s,
      rw [set.mem_union] at *,
      cases s_in_XY with s_in_X s_in_Y,

      left,
      apply X.subset_closed s;
      assumption,

      right,
      apply Y.subset_closed s;
      assumption,
    end)

@[reducible]
instance : has_union (simplicial_complex α) := ⟨simplicial_union⟩

lemma simplicial_union_assoc
    (X Y Z : simplicial_complex α)
  : (X ∪ Y) ∪ Z = X ∪ (Y ∪ Z)
:= begin
  simp,
  rw [set.union_assoc],
end

lemma simplicial_union_comm
    (X Y : simplicial_complex α)
  : X ∪ Y = Y ∪ X
:= begin
  simp,
  rw [set.union_comm],
end

@[simp]
def simplicial_inter
    (X Y : simplicial_complex α)
  : simplicial_complex α
:= simplicial_complex.mk
    (X.simplices ∩ Y.simplices)
    (begin
      rw [set.nonempty_coe_sort],
      rw [set.inter_nonempty],
      use ∅,
      split;
      apply simplicial_complex_empty_simplex,
    end)
    (begin
      unfold is_subset_closed,
      intros s s_in_XY t t_sset_s,
      rw [set.mem_inter_iff] at *,
      cases s_in_XY with s_in_X s_in_Y,
      split,

      apply X.subset_closed s;
      assumption,

      apply Y.subset_closed s;
      assumption,
    end)
    
@[reducible]
instance : has_inter (simplicial_complex α) := ⟨simplicial_inter⟩

lemma simplicial_inter_assoc
    (X Y Z : simplicial_complex α)
  : (X ∩ Y) ∩ Z = X ∩ (Y ∩ Z)
:= begin
  simp,
  rw [set.inter_assoc],
end

lemma simplicial_inter_comm
    (X Y : simplicial_complex α)
  : X ∩ Y = Y ∩ X
:= begin
  simp,
  rw [set.inter_comm],
end

end operators

/-
# Subcomplexes
-/

-- Define a subcomplex in the usual way:
-- i.e., simplices are contained in the other.
def is_subcomplex
    (X Y : simplicial_complex α)
  : Prop
:= X.simplices ⊆ Y.simplices

@[reducible]
instance : has_subset (simplicial_complex α) := ⟨is_subcomplex⟩

-- Equivalent, useful definition of a simplex as a subcomplex of the original.
def is_simplex
    (s : finset α)
    (X : simplicial_complex α)
  : Prop
:= (simplex s) ⊆ X

@[reducible]
instance : has_mem (finset α) (simplicial_complex α) := ⟨is_simplex⟩

-- This is, in fact, equivalent to our definition.
lemma simplex_iff_subcomplex
    (X : simplicial_complex α)
    (s : finset α)
  : s ∈ X.simplices ↔ s ∈ X
:= begin
  split; simp,

  intro s_in_X_simpl,
  simp only[is_simplex, is_subcomplex, simplex],
  rw [set.subset_def],
  intros x x_in_s_power,
  apply X.subset_closed s,
  assumption,
  rw [finset.mem_coe, finset.mem_powerset] at x_in_s_power,
  assumption,

  intro s_simpl_X,
  simp only[is_simplex, is_subcomplex, simplex] at s_simpl_X,
  rw [set.subset_def] at s_simpl_X,
  specialize s_simpl_X s,
  rw [finset.mem_coe] at s_simpl_X,
  specialize s_simpl_X (finset.mem_powerset_self s),
  assumption,
end