/-
Copyright (c) 2022 Clara Löh. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.txt.
Author: Clara Löh.
-/

import tactic          -- standard proof tactics
import data.set.basic        -- basics on sets
import data.set.finite -- basics on finite sets
import data.finset.basic     -- type-level finite sets

open_locale big_operators

variables {α : Type*}

/- 
# Simplicial complexes
-/

/- A simplicial complex is a set of finite sets 
   that is closed under taking subsets;
   we use finsets to model these finite sets
-/   

@[simp]
def is_subset_closed
    (S : set (finset α))
:= ∀ s ∈ S, ∀ t, t ⊆ s → t ∈ S    

structure simplicial_complex (α : Type*)
:= mk :: (simplices : set (finset α))
         (nonempty : nonempty simplices)
         (subset_closed : is_subset_closed simplices)

lemma eq_simplices_subset_closed
    (S T : set (finset α))
  : S = T → is_subset_closed S → is_subset_closed T
:=
begin
  intros S_eq_T subset_closed_S,
  subst S_eq_T,
  exact subset_closed_S,
end

lemma simplicial_complex_empty_simplex
    (X : simplicial_complex α)
  : ∅ ∈ X.simplices
:= begin
  have H : nonempty X.simplices, by apply X.nonempty,
  rw [set.nonempty_coe_sort, set.nonempty_def] at H,
  choose s Hs using H,
  apply X.subset_closed s; tauto,
end

-- The empty simplicial complex
def empty_sc 
    {a : Type*}
  : simplicial_complex a
:= simplicial_complex.mk  
     ({∅} : set (finset a))
     (by { rw [set.nonempty_coe_sort, set.nonempty_def], use ∅, simp, })
     (begin
        unfold is_subset_closed,
        intros s H_empty t t_sset_s,
        rw [set.mem_singleton_iff] at H_empty,
        rw [H_empty, finset.subset_empty] at t_sset_s,
        tauto,
      end)

/- The set of vertices of a simplicial complex is 
   the set of all elements 
   that occur in at least one of the simplices.
-/
def vertices 
    (X : simplicial_complex α)
  : set α
:= ⋃ (s : finset α) (H : s ∈ X.simplices), s

lemma vertices_set_of
    (X : simplicial_complex α)
  : vertices X = { x : α | ∃ s ∈ X.simplices, x ∈ s }
:= begin
  simp only [vertices, set.ext_iff, set.mem_Union, set.mem_set_of],
  intro x,
  refl,
end

instance vertices.fintype
    [decidable_eq α]
    (X : simplicial_complex α) [fintype X.simplices]
  : fintype (vertices X)
:= begin
  unfold vertices,
  apply set.fintype_bUnion,
  intros s s_in_X,
  apply finset_coe.fintype,
end

lemma vertex_iff_singleton
    (X : simplicial_complex α)
    (x : α)
  : x ∈ vertices X ↔ {x} ∈ X.simplices
:= begin
  split,

  intro x_vert,
  simp only[vertices, set.mem_Union] at x_vert,
  choose s Hs x_in_s using x_vert,
  apply X.subset_closed s,
  assumption,
  rw [finset.subset_iff],
  intros y y_eq_x,
  rw [finset.mem_singleton] at y_eq_x,
  rw [y_eq_x] at *,
  tauto,

  intro x_simpl,
  simp only[vertices, set.mem_Union],
  use {x},
  split,
  assumption,
  rw [finset.mem_coe, finset.mem_singleton],
end

-- The simplex generated by a finset
@[simp]
def simplex
    (V : finset α)
  : simplicial_complex α
:= simplicial_complex.mk 
    (finset.powerset V)
    (begin
      rw [set.nonempty_coe_sort],
      apply finset.powerset_nonempty,
    end)
    (by { simp, tauto })

instance simplex.fintype
    (s : finset α)
  : fintype (simplex s).simplices
:= begin
  simp only [simplex, simplicial_complex.simplices],
  apply finset_coe.fintype,
end

instance simplex.finite
    (s : finset α)
  : finite (simplex s).simplices
:= begin
  simp only [simplex, simplicial_complex.simplices],
  rw [set.finite_coe_iff],
  apply set.finite.intro,
  apply finset_coe.fintype,
end

lemma simplex_vertices
    (x : α)
  : vertices (@simplex α {x}) = {x}
:= begin
  rw [vertices_set_of],
  simp only [set.ext_iff, set.mem_set_of, simplex, set.mem_singleton_iff],
  intro y,
  split,

  intro y_in_union,
  choose s s_in_simplex y_in_s using y_in_union,
  simp only [finset.mem_coe, finset.mem_powerset, finset.subset_singleton_iff] at s_in_simplex,
  cases s_in_simplex with s_empty s_ne,

  rw [finset.eq_empty_iff_forall_not_mem] at s_empty,
  specialize s_empty y,
  contradiction,

  subst s_ne,
  rw [finset.mem_singleton] at y_in_s,
  assumption,

  intro y_eq_x,
  subst y_eq_x,
  use {y}, split,
  rw [finset.mem_coe],
  apply finset.mem_powerset_self,
  apply finset.mem_singleton_self,
end

-- The standard n-simplex is generated by {0,...,n}
@[simp]
def std_simplex
    (n : ℕ)
  : simplicial_complex ℕ
:= simplex (finset.range (n + 1))

/-
# Dimension of simplices and simplicial complexes
-/

-- The dimension of a simplex is just its cardinality - 1. 
@[simp]
def dim
    (s : finset α)
  : ℤ
:= finset.card s - 1

@[simp]
def is_k_simplex
    (s : finset α)
    (k : ℕ)
:= dim s = k

#eval dim (finset.range 5) -- 4
#eval dim (finset.range 0) -- -1

-- A simplicial complex has dimension n 
-- if n is the maximal dimension of all simplices. 
@[simp]
def has_dimension_leq
    (X : simplicial_complex α)
    (n : ℕ)
:= ∀ s ∈ X.simplices, dim s ≤ n    

@[simp]
def has_dimension_geq
    (X : simplicial_complex α)
    (n : ℕ)
:= ∃ s ∈ X.simplices, dim s ≥ n    

@[simp]
def has_dimension
    (X : simplicial_complex α)
    (n : ℕ)
:= has_dimension_leq X n ∧ has_dimension_geq X n    

-- The standard n-simplex has dimension n
lemma dim_std_simplex
    (n : ℕ)
  : has_dimension (std_simplex n) n
:= begin
  let Dn := std_simplex n,

  -- dim ≤ n
  have dim_leq_n : has_dimension_leq Dn n, from
  begin
    assume s : finset nat,
    assume s_in_Dn : s ∈ Dn.simplices,

    -- By definition, s ⊆ {0,...,n}.
    have s_sub_n : s ⊆ finset.range (n+1), 
         by exact finset.mem_powerset.mp s_in_Dn,
    
    -- Thus, s has cardinality at most n + 1.
    have card_s_leq_n1 : finset.card s ≤ n + 1, from
    begin
      calc finset.card s ≤ finset.card (finset.range (n+1)) 
                         : by exact finset.card_le_of_subset s_sub_n
                     ... ≤ n + 1 
                         : by finish,
    end,

    -- Whence, s has dimension at most n
    show dim s ≤ n, from
    begin      
      calc dim s = finset.card s - 1 : by simp only [dim]
             ... ≤ n + 1 - 1         : by linarith 
             ... ≤ n                 : by linarith,
    end,
  end,

  -- dim ≥ n
  have dim_geq_n : has_dimension_geq Dn n, from
  begin
    -- We use {0,...,n} as a witness
    let s := finset.range (n+1),
    use s,

    have s_in_Dn : s ∈ (std_simplex n).simplices, 
         by simp,

    have dim_s : dim s ≥ n, 
         by finish,

    show _, by exact ⟨s_in_Dn, dim_s⟩, -- alternatively: and.intro ...
  end,

  show _, by exact ⟨dim_leq_n, dim_geq_n⟩,
end

lemma dim_geq_zero_iff_nonempty
    (s : finset α)
  : 0 ≤ dim s ↔ s ≠ ∅
:= begin
  unfold dim,
  rw [ne.def, ←finset.card_eq_zero],
  split,
  

  contrapose,
  simp only[not_not],
  intro s_card_zero,
  rw [s_card_zero],
  omega,

  intro s_card_ne_zero,
  have s_card_pos : s.card > 0, by omega,
  linarith,
end

lemma dim_neg_one_iff_empty
    (s : finset α)
  : dim s = -1 ↔ s = ∅
:= begin
  unfold dim,
  rw [←finset.card_eq_zero],
  split,

  intro s_card_neg_one,
  simp only [sub_eq_neg_self, nat.cast_eq_zero] at s_card_neg_one,
  assumption,

  intro s_card_zero,
  rw [s_card_zero],
  simp,
end

lemma dim_zero_iff_vertex
    (s : finset α)
  : dim s = 0 ↔ ∃ x : α, s = {x}
:= begin
  unfold dim,
  split,

  intro s_card_minus_one,
  have s_card_one : s.card = 1, by linarith,
  rw [←finset.card_eq_one],
  assumption,

  intro exists_x,
  rw [←finset.card_eq_one] at exists_x,
  rw [exists_x],
  simp,
end

-- TODO: Do we want a nonempty result on t as well?
lemma simplex_decomp [decidable_eq α]
    (s : finset α)
  : 0 < dim s → ∃ (x ∈ s) (t : finset α), t = s \ {x}
:= begin
  unfold dim,
  intro s_card_pos,

  have s_card_gt_one : 1 < s.card, by linarith,
  rw [finset.one_lt_card] at s_card_gt_one,
  choose a a_in_s b b_in_s a_ne_b using s_card_gt_one,

  use a, split, assumption,
  use (s \ {a}),
end

lemma simplex_decomp_dim [decidable_eq α]
    (s : finset α)
    (x : α)
    (x_in_s : x ∈ s)
  : 0 < dim s → 0 ≤ dim (s \ {x})
:= begin
  unfold dim,
  intro s_card_pos,

  have s_card_gt_one : 1 < s.card, by linarith,
  rw [finset.card_sdiff, finset.card_singleton],
  apply int.sub_nonneg_of_le,
  rw [int.coe_nat_sub, int.coe_nat_one, int.le_sub_one_iff],

  rw [nat.one_lt_cast],
  assumption,

  apply le_of_lt,
  assumption,

  rw [finset.singleton_subset_iff],
  assumption,
end

lemma simplex_decomp_dim_eq [decidable_eq α]
    (s : finset α)
    (x : α)
    (x_in_s : x ∈ s)
  : 0 < dim s → dim (s \ {x}) = dim s - 1
:= begin
  unfold dim,
  intro s_card_pos,
  rw [finset.card_sdiff, finset.card_singleton],
  rw [sub_left_inj, int.coe_nat_sub, int.coe_nat_one],

  linarith,

  rw [finset.singleton_subset_iff],
  assumption,
end

-- The dimension of a finite complex is the maximum
-- dimension of its simplices.
@[simp]
def dim_of_complex
    (X : simplicial_complex α) [fintype X.simplices]
  : int
:= match finset.max (finset.bUnion X.simplices.to_finset (λ s, {dim s})) with
    | option.none := -1   -- degenerate ∅ case
    | option.some z := z
  end

/-
# Disjointness of simplicial complexes.
-/
section disjoint

variable [decidable_eq α]

-- Define when two simplicial complexes are disjoint via disjointness of vertices.
def disjoint_complexes
    (X Y : simplicial_complex α)
  : Prop
:= disjoint (vertices X) (vertices Y)

-- Indeed, this implies simplices are disjoint, too.
lemma disjoint_simplices_iff_disj_vertices
    (X Y : simplicial_complex α)
    (s t : finset α)
    (s_in_X : s ∈ X.simplices)
    (t_in_Y : t ∈ Y.simplices)
  : disjoint_complexes X Y → disjoint s t
:= begin
  simp only[disjoint_complexes, vertices],
  intro XY_disj,

  rw [set.disjoint_iff_inter_eq_empty, ←set.subset_empty_iff] at XY_disj,
  rw [finset.disjoint_iff_inter_eq_empty, ←finset.subset_empty, ←finset.coe_subset, finset.coe_empty, finset.coe_inter],

  apply @set.subset.trans _ _
    ((⋃ (s : finset α) (H : s ∈ X.simplices), ↑s) ∩ ⋃ (s : finset α) (H : s ∈ Y.simplices), ↑ s),

  apply set.inter_subset_inter;
  apply set.subset_bUnion_of_mem; assumption,
  assumption,
end

-- Disjoint singletons are also disjoint.
lemma disjoint_singleton
    (X : simplicial_complex α)
    (x : α)
  : x ∉ vertices X → disjoint_complexes X (simplex {x})
:= begin
  simp only [disjoint_complexes, simplex_vertices],
  unfold vertices,
  intro x_nin_X,
  
  rw [set.disjoint_iff_inter_eq_empty, set.inter_singleton_eq_empty],
  assumption,
end

end disjoint

/-
# Operators on simplicial complexes.
-/

section operators

variables [decidable_eq α]

@[simp]
def simplicial_union
    (X Y : simplicial_complex α)
  : simplicial_complex α
:= simplicial_complex.mk
    (X.simplices ∪ Y.simplices)
    (begin
      rw [set.nonempty_coe_sort],
      rw [set.union_nonempty],
      left,
      rw [←set.nonempty_coe_sort],
      apply X.nonempty,
    end)
    (begin
      unfold is_subset_closed,
      intros s s_in_XY t t_sset_s,
      rw [set.mem_union] at *,
      cases s_in_XY with s_in_X s_in_Y,

      left,
      apply X.subset_closed s;
      assumption,

      right,
      apply Y.subset_closed s;
      assumption,
    end)

@[reducible]
instance : has_union (simplicial_complex α) := ⟨simplicial_union⟩

lemma simplicial_union_assoc
    (X Y Z : simplicial_complex α)
  : (X ∪ Y) ∪ Z = X ∪ (Y ∪ Z)
:= begin
  simp,
  rw [set.union_assoc],
end

lemma simplicial_union_comm
    (X Y : simplicial_complex α)
  : X ∪ Y = Y ∪ X
:= begin
  simp,
  rw [set.union_comm],
end

lemma simplicial_union_simplices
    (X Y : simplicial_complex α)
  : (X ∪ Y).simplices = X.simplices ∪ Y.simplices
:= begin
  simp only[simplicial_union],
end

@[simp]
def simplicial_inter
    (X Y : simplicial_complex α)
  : simplicial_complex α
:= simplicial_complex.mk
    (X.simplices ∩ Y.simplices)
    (begin
      rw [set.nonempty_coe_sort],
      rw [set.inter_nonempty],
      use ∅,
      split;
      apply simplicial_complex_empty_simplex,
    end)
    (begin
      unfold is_subset_closed,
      intros s s_in_XY t t_sset_s,
      rw [set.mem_inter_iff] at *,
      cases s_in_XY with s_in_X s_in_Y,
      split,

      apply X.subset_closed s;
      assumption,

      apply Y.subset_closed s;
      assumption,
    end)
    
@[reducible]
instance : has_inter (simplicial_complex α) := ⟨simplicial_inter⟩

lemma simplicial_inter_assoc
    (X Y Z : simplicial_complex α)
  : (X ∩ Y) ∩ Z = X ∩ (Y ∩ Z)
:= begin
  simp,
  rw [set.inter_assoc],
end

lemma simplicial_inter_comm
    (X Y : simplicial_complex α)
  : X ∩ Y = Y ∩ X
:= begin
  simp,
  rw [set.inter_comm],
end

end operators

/-
# Subcomplexes
-/

-- Define a subcomplex in the usual way:
-- i.e., simplices are contained in the other.
def is_subcomplex
    (X Y : simplicial_complex α)
  : Prop
:= X.simplices ⊆ Y.simplices

@[reducible]
instance : has_subset (simplicial_complex α) := ⟨is_subcomplex⟩

lemma is_subcomplex_vertices
    (X Y : simplicial_complex α)
    (Y_subcomp_X : Y ⊆ X)
  : vertices Y ⊆ vertices X
:= begin
  simp only [vertices, set.subset_def],
  simp only [simplicial_complex.has_subset, is_subcomplex, set.subset_def] at Y_subcomp_X,

  intros y y_in_vert_Y,
  simp only [set.mem_Union] at y_in_vert_Y ⊢,
  choose s Hs y_in_s using y_in_vert_Y,
  specialize Y_subcomp_X s Hs,

  use s, split, apply Y_subcomp_X,
  apply y_in_s,
end

-- Equivalent, useful definition of a simplex as a subcomplex of the original.
def is_simplex
    (s : finset α)
    (X : simplicial_complex α)
  : Prop
:= (simplex s) ⊆ X

@[reducible]
instance : has_mem (finset α) (simplicial_complex α) := ⟨is_simplex⟩

-- This is, in fact, equivalent to our definition.
lemma simplex_iff_subcomplex
    (X : simplicial_complex α)
    (s : finset α)
  : s ∈ X.simplices ↔ s ∈ X
:= begin
  split; simp,

  intro s_in_X_simpl,
  simp only[is_simplex, is_subcomplex, simplex],
  rw [set.subset_def],
  intros x x_in_s_power,
  apply X.subset_closed s,
  assumption,
  rw [finset.mem_coe, finset.mem_powerset] at x_in_s_power,
  assumption,

  intro s_simpl_X,
  simp only[is_simplex, is_subcomplex, simplex] at s_simpl_X,
  rw [set.subset_def] at s_simpl_X,
  specialize s_simpl_X s,
  rw [finset.mem_coe] at s_simpl_X,
  specialize s_simpl_X (finset.mem_powerset_self s),
  assumption,
end